#!/usr/bin/env python3
"""Generate the fuzz_p2p_decode seed corpus (fuzz/corpus/fuzz_p2p_decode/).

Sources, in provenance order:
  1. spore/docs/interop-vectors.json "fabric_v1" rpc2_*_frame_hex — the
     byte-exact golden rpc2 frames (same {M,S,E}+payload CBOR family as the
     p2p sync subset; generated by internal/secure, never hand-edited).
  2. Hand-minted hostile/regression shapes: the negint past-i64::MIN panic
     (fixed in p2p.rs, "found by the fuzz corpus"), the near-2^64 declared
     length (the Go decoder's wrap-crasher class), a depth bomb, and
     truncations of a well-formed frame.

Corpus files are RAW bytes (libFuzzer format, no header). Run after any
change to interop-vectors.json:

    python fuzz/gen_corpus.py            (from the spore-peer crate root)

Requires python3 with only the standard library. Locates the spore checkout
the same way src/fabric.rs's test helper does (sibling checkouts).
"""

import binascii
import glob
import json
import os
import struct
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "corpus", "fuzz_p2p_decode")

VECTOR_PATHS = [
    os.path.normpath(os.path.join(HERE, "..", "..", "spore", "docs", "interop-vectors.json")),
    os.path.normpath(os.path.join(HERE, "..", "spore", "docs", "interop-vectors.json")),
    os.path.normpath(os.path.join(HERE, "..", "..", "..", "spore", "docs", "interop-vectors.json")),
]


def locate_vectors():
    for p in VECTOR_PATHS:
        if os.path.exists(p):
            return p
    return None


def cbor_head(major, n):
    """CBOR head bytes (canonical fixed-length encoding for big n)."""
    if n < 24:
        return bytes([(major << 5) | n])
    if n <= 0xFF:
        return bytes([(major << 5) | 24, n])
    if n <= 0xFFFF:
        return bytes([(major << 5) | 25]) + struct.pack(">H", n)
    if n <= 0xFFFFFFFF:
        return bytes([(major << 5) | 26]) + struct.pack(">I", n)
    return bytes([(major << 5) | 27]) + struct.pack(">Q", n)


def cbor_text(s):
    b = s.encode()
    return cbor_head(3, len(b)) + b


def cbor_uint(v):
    return cbor_head(0, v)


def header(method, seq, err):
    out = cbor_head(5, 3)
    out += cbor_text("M") + cbor_text(method)
    out += cbor_text("S") + cbor_uint(seq)
    out += cbor_text("E") + cbor_text(err)
    return out


def chain_payload():
    # one [topoheight, blid(32B)] pair — the Peer.Chain response shape
    out = cbor_head(4, 1)
    out += cbor_head(4, 2)
    out += cbor_uint(7)
    out += cbor_head(2, 32) + b"\x09" * 32
    return out


def main():
    os.makedirs(OUT, exist_ok=True)
    for stale in glob.glob(os.path.join(OUT, "*")):
        os.remove(stale)

    written = []

    def emit(name, data):
        path = os.path.join(OUT, name)
        with open(path, "wb") as f:
            f.write(data)
        written.append(name)

    # 1. Golden frames from the interop vectors (byte-exact rpc2 family).
    vpath = locate_vectors()
    if vpath:
        with open(vpath, "r", encoding="utf-8") as f:
            vectors = json.load(f)
        for key, frame_hex in sorted(vectors["fabric_v1"].items()):
            if not key.startswith("rpc2_") or not key.endswith("_frame_hex"):
                continue
            emit(key[:-10] + ".bin", binascii.unhexlify(frame_hex))
        print(f"seeds: {sum(1 for w in written)} from {os.path.basename(vpath)}")
    else:
        print("seeds: spore/docs/interop-vectors.json not found — golden frames skipped",
              file=sys.stderr)

    # 2. Well-formed p2p shapes (Peer.Chain request/response round-trips).
    emit("chain_response_golden.bin", header("Peer.Chain", 42, "") + chain_payload())
    hs = cbor_head(5, 2) + cbor_text("H") + cbor_uint(999) + cbor_text("N") + cbor_uint(1)
    emit("handshake_response_golden.bin", header("", 1, "") + hs)
    put = (cbor_head(5, 2) + cbor_text("BLID") + cbor_head(2, 32) + b"\x07" * 32
           + cbor_text("BODY") + cbor_head(2, 12) + b"BINARY\x00DATA")
    emit("putobject_golden.bin", header("Peer.PutObject", 11, "") + put)

    # 3. Regression: negint magnitude past i64::MIN (panic found by the fuzz
    #    corpus, now rejected). Two boundary shapes: exactly i64::MIN is legal
    #    (must decode), one past it is hostile (must be rejected).
    emit("negint_i64min_boundary.bin", header("", 0, "") + cbor_head(1, 1 << 63))
    emit("negint_past_i64min.bin", header("", 0, "") + cbor_head(1, (1 << 63) + 1))

    # 4. Regression: near-2^64 declared lengths (the Go decoder's wrap class).
    emit("bstr_len_wrap.bin", header("", 0, "") + cbor_head(2, (1 << 64) - 1) + b"tail")
    emit("map_len_wrap.bin", header("", 0, "") + cbor_head(5, (1 << 64) - 1) + b"x")
    emit("text_len_2p40.bin", header("", 0, "") + cbor_head(3, 1 << 40) + b"short")

    # 5. Depth bomb: 100 nested arrays (1 byte each) past MAX_DEPTH=64.
    emit("depth_bomb_100.bin", header("", 0, "") + b"\x81" * 100 + b"\x00")

    # 6. Hostile text (invalid UTF-8 under a text major).
    emit("text_invalid_utf8.bin", header("", 0, "") + cbor_head(3, 4) + b"\xff\xfe\xfd\xfc")

    # 7. Truncations of the golden frame (decoder must return None, not panic).
    golden = header("Peer.Chain", 42, "") + chain_payload()
    for cut in (1, 2, 3, 5, 9, 17, len(golden) // 2, len(golden) - 1):
        emit(f"trunc_{cut:04d}.bin", golden[:cut])

    print(f"corpus: {len(written)} seeds in {os.path.relpath(OUT, HERE)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
