// SPDX-License-Identifier: BSD-3-Clause
//
//! fabric — relay-fabric verbs (freg/fput/fpop) on the spore-peer socket,
//! behind the -fabric flag (slice F1; docs/RELAY_FABRIC.md, WIRE_SPEC §8).
//!
//! A relay node stores queued 74-byte pointers per handle. The handle is the
//! DECIDED epoch-salted derivation — HKDF-SHA256(seed, label||epoch||sid) —
//! never the pointer's Route, so handles rotate with prekey-batch epochs and
//! don't link across relay-choice changes. Relays never learn sid (HKDF is
//! one-way) and never see the seed; they register the owner's possession
//! token at freg and require it back at fpop.
//!
//! The Go twin of every derivation here is spore/internal/fabric; the two
//! implementations must agree byte-for-byte, pinned by
//! spore/docs/interop-vectors.json "fabric_v1" (generated, never hand-edited).
//!
//! Design laws inherited (RELAY_FABRIC.md): the hold is reused — envelopes
//! are content-addressed `<cid>.fenv` files beside the body store, written
//! temp+rename, rebuilt into the in-memory index on startup. Relays validate
//! envelope SHAPE only (design law 4: the ratchet is the filter).

// The derivation fns are exercised by the vector-conformance tests now; the
// fabric CLIENT that computes handles/tokens on the wire is slice F2, until
// which the binary crate sees them as dead code.
#![allow(dead_code)]

use std::collections::HashMap;
use std::sync::Mutex;

use sha2::{Digest, Sha256};

use super::{ct_eq, frame_err, frame_ok, now_sec, write_frame, RateLimiter, ServeConfig};

// --- wire constants (must mirror spore/internal/fabric exactly) ---

pub const LABEL_HANDLE: &[u8] = b"spore/fabric/v1/handle";
pub const LABEL_REG: &[u8] = b"spore/fabric/v1/reg";
pub const ENVELOPE_V1: u8 = 1;
pub const POINTER_LEN: usize = 74;
pub const ENVELOPE_LEN: usize = 1 + 32 + POINTER_LEN + 8;

// --- derivations (Go twin: internal/fabric.FabricHandle / RegToken) ---

/// RFC 2104 HMAC-SHA256, hand-rolled to keep the dependency list at
/// serde_json/hex/sha2. Verified against the interop vectors, which were
/// generated by Go's crypto/hmac — agreement is proven, not assumed.
pub fn hmac_sha256(key: &[u8], data: &[u8]) -> [u8; 32] {
    // Keys longer than the block are hashed first (RFC 2104 §2).
    let mut k = [0u8; 64];
    if key.len() > 64 {
        k[..32].copy_from_slice(&Sha256::digest(key));
    } else {
        k[..key.len()].copy_from_slice(key);
    }
    let mut ipad = [0x36u8; 64];
    let mut opad = [0x5cu8; 64];
    for i in 0..64 {
        ipad[i] ^= k[i];
        opad[i] ^= k[i];
    }
    let mut inner = Sha256::new();
    inner.update(ipad);
    inner.update(data);
    let ih = inner.finalize();
    let mut outer = Sha256::new();
    outer.update(opad);
    outer.update(ih);
    outer.finalize().into()
}

/// HKDF-SHA256 Extract with a ZERO salt — RFC 5869's default, and what Go's
/// golang.org/x/crypto/hkdf does with a nil salt (the ratchet's hkdfExpand
/// discipline). The zero-salt choice is load-bearing: Go's hkdf.New with nil
/// salt zero-fills the salt block, so a salted Rust Extract would derive
/// different handles than every Go peer.
fn hkdf_prk(ikm: &[u8]) -> [u8; 32] {
    hmac_sha256(&[0u8; 32], ikm)
}

/// HKDF-Expand per RFC 5869: T(i) = HMAC(PRK, T(i-1) || info || i), T(0) empty.
fn hkdf_expand(prk: &[u8; 32], info: &[u8], n: usize) -> Vec<u8> {
    let mut okm = Vec::with_capacity(n);
    let mut t: Vec<u8> = Vec::new();
    let mut counter: u8 = 1;
    while okm.len() < n {
        let mut msg = t.clone();
        msg.extend_from_slice(info);
        msg.push(counter);
        t = hmac_sha256(prk, &msg).to_vec();
        okm.extend_from_slice(&t);
        counter += 1;
    }
    okm.truncate(n);
    okm
}

/// FabricHandle = HKDF-SHA256(seed, LABEL_HANDLE || epoch_be || sid)[..32].
///
/// The epoch-salted lookup handle relays index by. The pointer's Route stays
/// RouteKey(sid) (the pointer plane is untouched; the recipient's FetchFrame
/// binding holds). seed is the 32-byte contact-card secret; epoch increments
/// on prekey-batch rotation; sid is the ratchet session id.
pub fn fabric_handle(seed: &[u8; 32], epoch: u32, sid: &[u8; 8]) -> [u8; 32] {
    let prk = hkdf_prk(seed);
    let mut info = Vec::with_capacity(LABEL_HANDLE.len() + 4 + 8);
    info.extend_from_slice(LABEL_HANDLE);
    info.extend_from_slice(&epoch.to_be_bytes());
    info.extend_from_slice(sid);
    let out = hkdf_expand(&prk, &info, 32);
    let mut h = [0u8; 32];
    h.copy_from_slice(&out);
    h
}

/// token = hex(HMAC-SHA256(seed, LABEL_REG || handle || server_nonce)).
///
/// Possession of the seed, not knowledge of the public handle, drains.
/// Computed by the RECIPIENT (the only seed holder); the relay stores and
/// echoes it — no signature scheme exists here on purpose: a signature would
/// hand relays a cross-relay identity key, the exact linkage epochs exist to
/// break.
pub fn reg_token_hex(seed: &[u8; 32], handle: &[u8; 32], server_nonce: &str) -> String {
    let mut msg = Vec::with_capacity(LABEL_REG.len() + 32 + server_nonce.len());
    msg.extend_from_slice(LABEL_REG);
    msg.extend_from_slice(handle);
    msg.extend_from_slice(server_nonce.as_bytes());
    hex::encode(hmac_sha256(seed, &msg))
}

// --- envelope (Go twin: internal/fabric.Envelope) ---

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Envelope {
    pub handle: [u8; 32],
    pub pointer: [u8; POINTER_LEN], // PointerPayload verbatim; CID + deadline inside
    pub received_at: u64,           // unix-seconds, FIFO order + diagnostics
}

/// version u8 =1 | handle 32 | pointer 74 | received_at u64 LE
pub fn marshal_envelope(e: &Envelope) -> [u8; ENVELOPE_LEN] {
    let mut out = [0u8; ENVELOPE_LEN];
    out[0] = ENVELOPE_V1;
    out[1..33].copy_from_slice(&e.handle);
    out[33..33 + POINTER_LEN].copy_from_slice(&e.pointer);
    out[33 + POINTER_LEN..].copy_from_slice(&e.received_at.to_le_bytes());
    out
}

/// Structural validation only (shape, version, pointer header) — never
/// pointer semantics (the ratchet is the filter).
pub fn parse_envelope(b: &[u8]) -> Result<Envelope, String> {
    if b.len() != ENVELOPE_LEN {
        return Err(format!(
            "400 bad envelope length {} != {}",
            b.len(),
            ENVELOPE_LEN
        ));
    }
    if b[0] != ENVELOPE_V1 {
        return Err(format!("400 bad envelope version {}", b[0]));
    }
    let mut e = Envelope {
        handle: [0u8; 32],
        pointer: [0u8; POINTER_LEN],
        received_at: 0,
    };
    e.handle.copy_from_slice(&b[1..33]);
    e.pointer.copy_from_slice(&b[33..33 + POINTER_LEN]);
    if e.pointer[0] != 1 || e.pointer[1] != 0 {
        return Err("400 bad pointer payload header".to_string());
    }
    let mut le = [0u8; 8];
    le.copy_from_slice(&b[33 + POINTER_LEN..]);
    e.received_at = u64::from_le_bytes(le);
    Ok(e)
}

// --- relay-side state ---

/// Fabric knob set (the -fabric flag family). Disabled unless enabled.
#[derive(Clone)]
pub struct FabricConfig {
    pub enabled: bool,
    /// Per-handle queue cap: FIFO, evict-oldest (compost, don't hoard).
    pub max_per_handle: usize,
    /// freg lease cap in seconds (lease <= min(requested, this); default 7d).
    pub max_lease_sec: u64,
    /// fput per-IP per-second rate (the body path's window shape).
    pub fput_rate: u32,
    /// Registry budget: max LIVE freg registrations. freg is
    /// unauthenticated, so memory — not just rate — needs a hard ceiling.
    pub max_regs: usize,
}

impl Default for FabricConfig {
    fn default() -> Self {
        FabricConfig {
            enabled: false,
            max_per_handle: 32,
            max_lease_sec: 7 * 24 * 3600,
            fput_rate: 60,
            max_regs: 50_000,
        }
    }
}

struct Registration {
    token: String,
    expires: u64,
}

struct Queued {
    pointer: [u8; POINTER_LEN],
    env_cid_hex: String, // content address of the persisted envelope
    deadline: u64,
    received_at: u64,
}

/// Mutable fabric state shared across connections via ServeConfig.
/// Registrations are memory-only (a relay restart requires re-freg — leases
/// are ephemeral by contract); queues persist as .fenv files and rebuild.
pub struct FabricState {
    pub cfg: FabricConfig,
    fput_limiter: RateLimiter,
    reg: Mutex<HashMap<String, Registration>>, // handle_hex -> reg
    queues: Mutex<HashMap<String, Vec<Queued>>>, // handle_hex -> FIFO
}

impl FabricState {
    /// Open state for a hold dir: rebuild the queue index from *.fenv files
    /// (restart safety — same temp+rename discipline the body store uses).
    pub fn open(dir: &str, cfg: FabricConfig) -> FabricState {
        let st = FabricState {
            fput_limiter: RateLimiter::new(cfg.fput_rate),
            reg: Mutex::new(HashMap::new()),
            queues: Mutex::new(HashMap::new()),
            cfg,
        };
        let mut queues = st.queues.lock().unwrap();
        if let Ok(rd) = std::fs::read_dir(dir) {
            for ent in rd.flatten() {
                let p = ent.path();
                if p.extension().and_then(|e| e.to_str()) != Some("fenv") {
                    continue;
                }
                let Some(raw) = std::fs::read(&p).ok() else {
                    continue;
                };
                let Ok(env) = parse_envelope(&raw) else {
                    let _ = std::fs::remove_file(&p); // corrupt envelope: compost
                    continue;
                };
                let name = p.file_name().unwrap().to_string_lossy().to_string();
                let env_cid_hex = name.trim_end_matches(".fenv").to_string();
                let deadline = u64::from_le_bytes(env.pointer[66..74].try_into().unwrap());
                if deadline <= now_sec() {
                    // Envelope expired while the node was down: the burn
                    // deadline has passed, so the pointer is worthless to the
                    // recipient — compost instead of re-indexing.
                    let _ = std::fs::remove_file(&p);
                    continue;
                }
                queues
                    .entry(hex::encode(env.handle))
                    .or_default()
                    .push(Queued {
                        pointer: env.pointer,
                        env_cid_hex,
                        deadline,
                        received_at: env.received_at,
                    });
            }
        }
        for q in queues.values_mut() {
            q.sort_by_key(|x| (x.received_at, x.env_cid_hex.clone()));
        }
        drop(queues);
        st
    }

    fn persist_envelope(dir: &str, env_cid_hex: &str, raw: &[u8]) -> Result<(), String> {
        let tmp = format!("{}/{}.tmp", dir, env_cid_hex);
        let fin = format!("{}/{}.fenv", dir, env_cid_hex);
        std::fs::write(&tmp, raw).map_err(|e| format!("500 envelope write: {e}"))?;
        // Temp+rename: a crash mid-write never leaves a partial .fenv.
        std::fs::rename(&tmp, &fin).map_err(|e| format!("500 envelope rename: {e}"))
    }

    fn drop_envelope(dir: &str, env_cid_hex: &str) {
        let _ = std::fs::remove_file(format!("{}/{}.fenv", dir, env_cid_hex));
    }
}

// --- verb handlers (JSON request already parsed; response frame written) ---

/// Dispatch one fabric verb. `req` is the parsed JSON object; the "verb"
/// field selects freg/fput/fpop. Every response is the status-prefixed
/// legacy frame: 0x00 + JSON payload, or 0x01 + "NNN text".
pub fn handle_verb(
    s: &mut std::net::TcpStream,
    req: &serde_json::Value,
    dir: &str,
    cfg: &ServeConfig,
    ip: &str,
) {
    let Some(st) = cfg.fabric.as_ref() else {
        let _ = write_frame(s, &frame_err("501 fabric disabled"));
        return;
    };
    match req.get("verb").and_then(|v| v.as_str()) {
        Some("freg") => freg(s, st, req),
        Some("fput") => fput(s, st, req, dir, ip),
        Some("fpop") => fpop(s, st, req, dir, ip),
        _ => {
            let _ = write_frame(s, &frame_err("400 bad fabric verb"));
        }
    }
}

/// freg {handle, token, prev_token?, lease?} → 0x00 {token, expires}
///
/// Registers/refreshes a handle with the owner's possession token. The relay
/// cannot verify the token against a seed (it holds none) — possession is
/// enforced by requiring the token back at fpop. Two adversarial gates make
/// the registry unattractive to abuse (F1 adversarial review):
///
/// 1. CHAINED REFRESH: overwriting a LIVE registration requires prev_token
///    to match the current registration's token — only the seed holder can
///    renew or rotate. Without this, any third party who learns the (public)
///    handle could re-register it under their own token and drain the
///    victim's queue. An EXPIRED registration is fair game again (it has
///    become a squatter target exactly like a fresh handle).
///
/// 2. BUDGET + SWEEP: `max_regs` caps live registrations (default 50_000,
///    per the body store's quota shape). A full budget of live entries →
///    503: freg is unauthenticated, so the cap — not memory growth — is the
///    DoS answer. New registrations evict nothing of others.
///
/// Token shape: 16..=128 bytes. The floor closes an auth bypass — fpop
/// defaults a missing token to "", so an empty/1-char token would make the
/// queue drainable by anyone; the ceiling bounds registry memory per entry.
/// Handles are normalized to lowercase hex before use (hex case is not
/// identity; the mixed-case variant must not split into a second slot).
fn freg(s: &mut std::net::TcpStream, st: &FabricState, req: &serde_json::Value) {
    let Some(h) = req.get("handle").and_then(|v| v.as_str()) else {
        let _ = write_frame(s, &frame_err("400 freg needs handle"));
        return;
    };
    if !hex::decode(h).map(|b| b.len() == 32).unwrap_or(false) {
        let _ = write_frame(s, &frame_err("400 handle must be 32-byte hex"));
        return;
    }
    let h = h.to_lowercase();
    let Some(token) = req.get("token").and_then(|v| v.as_str()) else {
        let _ = write_frame(s, &frame_err("400 freg needs token"));
        return;
    };
    if !(16..=128).contains(&token.len()) {
        let _ = write_frame(s, &frame_err("400 token must be 16..=128 bytes"));
        return;
    }
    let now = now_sec();
    let lease = req.get("lease").and_then(|v| v.as_u64()).unwrap_or(3600);
    let expires = now + lease.min(st.cfg.max_lease_sec);
    let mut reg = st.reg.lock().unwrap();
    reg.retain(|_, r| r.expires > now); // expired entries hold nothing but memory
    if let Some(cur) = reg.get(&h) {
        // LIVE registration: only the current token holder may renew/rotate.
        let prev = req.get("prev_token").and_then(|v| v.as_str()).unwrap_or("");
        if !ct_eq(&cur.token, prev) {
            let _ = write_frame(s, &frame_err("403 live registration: prev_token required"));
            return;
        }
    } else if reg.len() >= st.cfg.max_regs {
        // Unauthenticated verb: the cap — not memory growth — is the DoS
        // answer. Full budget of live regs → refuse; new regs evict nothing.
        let _ = write_frame(s, &frame_err("503 fabric registry full"));
        return;
    }
    reg.insert(
        h,
        Registration {
            token: token.to_string(),
            expires,
        },
    );
    drop(reg);
    let body = serde_json::json!({ "token": token, "expires": expires });
    let _ = write_frame(s, &frame_ok(body.to_string().as_bytes()));
}

/// fput {handle, pointer_hex, deadline} → 0x00 {queued} | 404 | 410 | 429
///
/// Queue a pointer envelope at a registered handle. Checks, in order:
/// handle registered (404), per-IP rate (429), pointer is exactly 74 bytes
/// with a v1 header and nonzero deadline (400), deadline in the future
/// (410). Dedupe on (handle, pointer CID): re-publishing refreshes the
/// deadline, never duplicates. Over cap: evict oldest (compost, don't
/// hoard). The envelope is content-addressed into the hold as <cid>.fenv.
///
/// REAP STORY (F1 adversarial review, contract): there is no live ticker —
/// past-deadline envelopes compost at the next fpop drain, at the next
/// open() rebuild, or here, when a dedupe replaces them. The worst case a
/// crash-hard node accumulates is max_per_handle expired envelopes per
/// live registration, all bounded by the cap, all gone at the next touch.
fn fput(
    s: &mut std::net::TcpStream,
    st: &FabricState,
    req: &serde_json::Value,
    dir: &str,
    ip: &str,
) {
    let Some(h) = req.get("handle").and_then(|v| v.as_str()) else {
        let _ = write_frame(s, &frame_err("400 fput needs handle"));
        return;
    };
    if h.len() != 64 {
        // Hex lowercase or uppercase both decode to 32 bytes; 64 chars is
        // the exact length — refuse everything else before decoding.
        let _ = write_frame(s, &frame_err("400 handle must be 32-byte hex"));
        return;
    }
    let h = h.to_lowercase();
    {
        let reg = st.reg.lock().unwrap();
        match reg.get(&h) {
            None => {
                let _ = write_frame(s, &frame_err("404 unknown handle"));
                return;
            }
            Some(r) if r.expires <= now_sec() => {
                let _ = write_frame(s, &frame_err("404 handle lease expired"));
                return;
            }
            Some(_) => {}
        }
    }
    if !st.fput_limiter.allow(ip, now_sec()) {
        let _ = write_frame(s, &frame_err("429 fput rate"));
        return;
    }
    let Some(ptr_hex) = req.get("pointer_hex").and_then(|v| v.as_str()) else {
        let _ = write_frame(s, &frame_err("400 fput needs pointer_hex"));
        return;
    };
    if ptr_hex.len() != 2 * POINTER_LEN {
        let _ = write_frame(s, &frame_err("400 pointer must be 74-byte hex"));
        return;
    }
    let pointer = match hex::decode(ptr_hex) {
        Ok(p) if p.len() == POINTER_LEN => {
            let mut a = [0u8; POINTER_LEN];
            a.copy_from_slice(&p);
            a
        }
        _ => {
            let _ = write_frame(s, &frame_err("400 pointer must be 74-byte hex"));
            return;
        }
    };
    if pointer[0] != 1 || pointer[1] != 0 {
        let _ = write_frame(s, &frame_err("400 bad pointer payload header"));
        return;
    }
    let deadline = u64::from_le_bytes(pointer[66..74].try_into().unwrap());
    if deadline == 0 {
        let _ = write_frame(s, &frame_err("400 zero pointer deadline"));
        return;
    }
    if deadline <= now_sec() {
        let _ = write_frame(s, &frame_err("410 gone"));
        return;
    }
    let env = Envelope {
        handle: {
            let mut a = [0u8; 32];
            a.copy_from_slice(&hex::decode(&h).unwrap());
            a
        },
        pointer,
        received_at: now_sec(),
    };
    let raw = marshal_envelope(&env);
    let mut ec = Sha256::new();
    ec.update(raw);
    let env_cid_hex = hex::encode(ec.finalize());
    if let Err(e) = FabricState::persist_envelope(dir, &env_cid_hex, &raw) {
        let _ = write_frame(s, &frame_err(&e));
        return;
    }
    let mut queues = st.queues.lock().unwrap();
    let q = queues.entry(h.to_string()).or_default();
    if let Some(old) = q.iter_mut().find(|x| x.pointer == pointer) {
        // Dedupe: refresh the deadline in place. The envelope bytes include
        // received_at, so a refresh can re-persist under a NEW cid — then the
        // superseded file must compost, or it lingers on disk and resurrects
        // as a duplicate at the next restart rebuild. But if the bytes came
        // out identical (same received_at), old and new cid are the SAME
        // file: dropping it would orphan the queue entry's only copy and
        // silently lose the envelope at the next restart.
        old.deadline = deadline;
        if old.env_cid_hex != env_cid_hex {
            FabricState::drop_envelope(dir, &old.env_cid_hex);
            old.env_cid_hex = env_cid_hex;
        }
    } else {
        q.push(Queued {
            pointer,
            env_cid_hex,
            deadline,
            received_at: env.received_at,
        });
        while q.len() > st.cfg.max_per_handle {
            let evicted = q.remove(0); // oldest
            FabricState::drop_envelope(dir, &evicted.env_cid_hex);
        }
    }
    // A queued entry whose deadline passed while nobody drained: compost
    // it and anything else already burned — drain-time, not ticker-time.
    let now = now_sec();
    q.retain(|x| {
        if x.deadline <= now {
            FabricState::drop_envelope(dir, &x.env_cid_hex);
            false
        } else {
            true
        }
    });
    let _ = write_frame(s, &frame_ok(b"{\"queued\":true}"));
}

/// fpop {handle, token, max} → 0x00 {pointers: [...]} | 404 | 403
///
/// Drain up to max queued pointers, oldest first, deleting on read
/// (compost-on-read; entries whose deadline passed while queued compost
/// here too — the drain is a reap point, there is no ticker). Wrong token
/// is 403 (constant-time compare); unknown handle 404. fpop shares fput's
/// per-IP rate window: both are unauthenticated parser paths and neither
/// should be cheaper to flood than the other. Returns 74-byte pointer hex
/// strings — exactly what the recipient feeds into E2 ingestion, where
/// FetchFrame re-checks RouteKey(sid) == p.Route.
fn fpop(
    s: &mut std::net::TcpStream,
    st: &FabricState,
    req: &serde_json::Value,
    dir: &str,
    ip: &str,
) {
    let Some(h) = req.get("handle").and_then(|v| v.as_str()) else {
        let _ = write_frame(s, &frame_err("400 fpop needs handle"));
        return;
    };
    if h.len() != 64 {
        let _ = write_frame(s, &frame_err("400 handle must be 32-byte hex"));
        return;
    }
    let h = h.to_lowercase();
    let token = req.get("token").and_then(|v| v.as_str()).unwrap_or("");
    let max = req.get("max").and_then(|v| v.as_u64()).unwrap_or(8).min(64) as usize;
    if !st.fput_limiter.allow(ip, now_sec()) {
        let _ = write_frame(s, &frame_err("429 fpop rate"));
        return;
    }
    let reg = st.reg.lock().unwrap();
    let Some(r) = reg.get(&h) else {
        let _ = write_frame(s, &frame_err("404 unknown handle"));
        return;
    };
    if r.expires <= now_sec() || !ct_eq(&r.token, token) {
        let _ = write_frame(s, &frame_err("403 wrong token"));
        return;
    }
    drop(reg);
    let now = now_sec();
    let mut out: Vec<String> = Vec::new();
    let mut queues = st.queues.lock().unwrap();
    if let Some(q) = queues.get_mut(&h) {
        while out.len() < max && !q.is_empty() {
            let item = q.remove(0);
            FabricState::drop_envelope(dir, &item.env_cid_hex);
            if item.deadline > now {
                out.push(hex::encode(item.pointer));
            }
            // else: expired while queued — composted, not delivered.
        }
    }
    let body = serde_json::json!({ "pointers": out });
    let _ = write_frame(s, &frame_ok(body.to_string().as_bytes()));
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Locate spore/docs/interop-vectors.json across the known checkout
    /// layouts; None means spore is absent (spore-peer's own CI) and the
    /// vector tests SKIP — a layout fact, not a conformance failure.
    fn vectors_path() -> Option<std::path::PathBuf> {
        let manifest = env!("CARGO_MANIFEST_DIR");
        for candidate in [
            "../../spore/docs/interop-vectors.json",
            "../spore/docs/interop-vectors.json",
            "../../../spore/docs/interop-vectors.json",
            "../docs/interop-vectors.json",
        ] {
            let p = std::path::Path::new(manifest).join(candidate);
            if p.exists() {
                return Some(p);
            }
        }
        None
    }

    fn field<'a>(v: &'a serde_json::Value, name: &str) -> &'a str {
        v.get(name)
            .and_then(|x| x.as_str())
            .unwrap_or_else(|| panic!("vector file missing {name}"))
    }

    /// Vectors-first conformance: Go generated the file; Rust must agree
    /// byte-for-byte on handles, tokens, and the envelope codec — and must
    /// FAIL against every negative vector.
    #[test]
    fn fabric_vectors_conformance() {
        let Some(p) = vectors_path() else { return };
        let raw = std::fs::read_to_string(p).unwrap();
        let v: serde_json::Value = serde_json::from_str(&raw).unwrap();
        let fv = &v["fabric_v1"];

        let seed = hex::decode(field(fv, "seed_hex")).unwrap();
        let mut seed32 = [0u8; 32];
        seed32.copy_from_slice(&seed);
        let sid = hex::decode(field(fv, "sid_hex")).unwrap();
        let mut sid8 = [0u8; 8];
        sid8.copy_from_slice(&sid);
        let epoch: u32 = field(fv, "epoch").parse().unwrap();

        let h = fabric_handle(&seed32, epoch, &sid8);
        assert_eq!(hex::encode(h), field(fv, "handle_hex"));

        let h8 = fabric_handle(&seed32, epoch + 1, &sid8);
        assert_eq!(hex::encode(h8), field(fv, "handle_negative_epoch8_hex"));
        assert_ne!(h, h8, "different epochs must derive different handles");

        let nonce = field(fv, "reg_server_nonce");
        let tok = reg_token_hex(&seed32, &h, nonce);
        assert_eq!(tok, field(fv, "reg_token_hex"));
        let tok_x = reg_token_hex(&seed32, &h, &format!("{nonce}-x"));
        assert_eq!(tok_x, field(fv, "reg_token_negative_other_nonce_hex"));
        assert_ne!(tok, tok_x, "a different nonce must not open the queue");

        let env = parse_envelope(&hex::decode(field(fv, "envelope_hex")).unwrap()).unwrap();
        assert_eq!(hex::encode(env.handle), field(fv, "handle_hex"));
        assert_eq!(hex::encode(env.pointer), field(fv, "pointer_hex"));
        assert_eq!(
            env.received_at.to_string(),
            field(fv, "envelope_received_at")
        );
        assert_eq!(
            hex::encode(marshal_envelope(&env)),
            field(fv, "envelope_hex"),
            "marshal(parse(x)) == x"
        );

        let bad = hex::decode(field(fv, "envelope_negative_bad_version_hex")).unwrap();
        assert!(parse_envelope(&bad).is_err(), "wrong version must fail");
        assert!(
            parse_envelope(&hex::decode(field(fv, "pointer_negative_len73_hex")).unwrap()[..73])
                .is_err(),
            "short pointer must fail"
        );
    }

    // --- end-to-end verb tests over real sockets ---

    use super::super::tests::{frame, mk_temp_dir};
    use std::io::{Read, Write};

    /// One fabric request over a frame: JSON in, (status, payload) out.
    fn rpc(c: &mut std::net::TcpStream, req: serde_json::Value) -> (u8, serde_json::Value) {
        c.write_all(&frame(req.to_string().as_bytes())).unwrap();
        let mut buf = [0u8; 4];
        c.read_exact(&mut buf).unwrap();
        let len = u32::from_le_bytes(buf) as usize;
        let mut payload = vec![0u8; len];
        c.read_exact(&mut payload).unwrap();
        let status = payload[0];
        let body = serde_json::from_slice(&payload[1..]).unwrap_or(serde_json::Value::Null);
        (status, body)
    }

    /// Spawn handle_client on a real socket with fabric enabled on `dir`.
    fn fabric_server(
        dir: &std::path::Path,
        fcfg: FabricConfig,
    ) -> (std::thread::JoinHandle<()>, String) {
        let listener = std::net::TcpListener::bind("127.0.0.1:0").unwrap();
        let addr = listener.local_addr().unwrap().to_string();
        let cfg = super::super::ServeConfig {
            fabric: Some(std::sync::Arc::new(FabricState::open(
                dir.to_str().unwrap(),
                fcfg,
            ))),
            ..Default::default()
        };
        let d = dir.to_path_buf();
        let server = std::thread::spawn(move || {
            let (stream, _) = listener.accept().unwrap();
            let mut s = stream;
            super::super::handle_client(
                &mut s,
                d.to_str().unwrap(),
                "127.0.0.1".to_string(),
                &cfg,
                &super::super::RateLimiter::new(0),
            );
        });
        (server, addr)
    }

    fn valid_pointer(deadline: u64, tag: u8) -> String {
        let mut p = vec![1u8, 0];
        p.extend_from_slice(&[tag; 32]); // route
        p.extend_from_slice(&[0xA5 + tag; 32]); // cid-ish
        p.extend_from_slice(&deadline.to_le_bytes());
        hex::encode(p)
    }

    fn fabric_cfg() -> FabricConfig {
        FabricConfig {
            enabled: true,
            ..Default::default()
        }
    }

    #[test]
    fn fabric_disabled_without_flag() {
        let dir = mk_temp_dir("fabric-off");
        let listener = std::net::TcpListener::bind("127.0.0.1:0").unwrap();
        let addr = listener.local_addr().unwrap().to_string();
        let d = dir.clone();
        let server = std::thread::spawn(move || {
            let (stream, _) = listener.accept().unwrap();
            let mut s = stream;
            super::super::handle_client(
                &mut s,
                d.to_str().unwrap(),
                "127.0.0.1".to_string(),
                &super::super::ServeConfig::default(),
                &super::super::RateLimiter::new(0),
            );
        });
        let mut c = std::net::TcpStream::connect(&addr).unwrap();
        let (status, _) = rpc(
            &mut c,
            serde_json::json!({"verb": "freg", "handle": "00", "token": "t"}),
        );
        assert_eq!(status, 0x01);
        drop(c);
        server.join().unwrap();
    }

    #[test]
    fn freg_fput_fpop_roundtrip_and_dedupe() {
        let dir = mk_temp_dir("fabric-rt");
        let (server, addr) = fabric_server(&dir, fabric_cfg());
        let mut c = std::net::TcpStream::connect(&addr).unwrap();
        let handle = "aa".repeat(32);
        let token = "tok-1234567890abcdef"; // 20 bytes: within the 16..=128 shape

        // Shape rule: a short token is refused before anything else.
        let (st, _) = rpc(
            &mut c,
            serde_json::json!({"verb":"freg","handle":handle,"token":"short","lease":60}),
        );
        assert_eq!(st, 0x01, "sub-16-byte token must be refused");

        let (st, body) = rpc(
            &mut c,
            serde_json::json!({"verb":"freg","handle":handle,"token":token,"lease":60}),
        );
        assert_eq!(st, 0x00, "freg: {body}");
        assert_eq!(body["token"], token, "relay echoes the possession token");

        // Chained refresh: a live registration may NOT be overwritten without
        // the current token (handle is public; possession is the only proof).
        let (st, _) = rpc(
            &mut c,
            serde_json::json!({"verb":"freg","handle":handle,"token":"attacker-token-1234","lease":60}),
        );
        assert_eq!(st, 0x01, "takeover without prev_token must be refused");
        let (st, _) = rpc(
            &mut c,
            serde_json::json!({"verb":"freg","handle":handle,"token":token,"prev_token":token,"lease":60}),
        );
        assert_eq!(st, 0x00, "renewal with prev_token succeeds");

        let ptr = valid_pointer(now_sec() + 600, 1);
        let (st, body) = rpc(
            &mut c,
            serde_json::json!({"verb":"fput","handle":handle,"pointer_hex":ptr,"deadline":now_sec()+600}),
        );
        assert_eq!(st, 0x00, "fput: {body}");
        // Dedupe: re-publishing the same pointer refreshes, never duplicates.
        let (st, _) = rpc(
            &mut c,
            serde_json::json!({"verb":"fput","handle":handle,"pointer_hex":ptr,"deadline":now_sec()+900}),
        );
        assert_eq!(st, 0x00);

        let (st, body) = rpc(
            &mut c,
            serde_json::json!({"verb":"fpop","handle":handle,"token":token,"max":8}),
        );
        assert_eq!(st, 0x00, "fpop: {body}");
        let ptrs = body["pointers"].as_array().unwrap();
        assert_eq!(ptrs.len(), 1, "dedupe: one entry, not two");
        assert_eq!(ptrs[0], ptr);

        // Compost-on-read: the queue is empty now.
        let (st, body) = rpc(
            &mut c,
            serde_json::json!({"verb":"fpop","handle":handle,"token":token,"max":8}),
        );
        assert_eq!(st, 0x00);
        assert_eq!(body["pointers"].as_array().unwrap().len(), 0);
        drop(c);
        server.join().unwrap();
    }

    #[test]
    fn hostile_frames_all_refused() {
        let dir = mk_temp_dir("fabric-hostile");
        let (server, addr) = fabric_server(&dir, fabric_cfg());
        let mut c = std::net::TcpStream::connect(&addr).unwrap();
        let handle = "bb".repeat(32);
        let token = "tok-1234567890abcdef"; // 20 bytes: within the shape rule
        let (st, _) = rpc(
            &mut c,
            serde_json::json!({"verb":"freg","handle":handle,"token":token,"lease":60}),
        );
        assert_eq!(st, 0x00);

        // fpop: wrong token 403, unknown handle 404.
        let (st, _) = rpc(
            &mut c,
            serde_json::json!({"verb":"fpop","handle":handle,"token":"wrong","max":8}),
        );
        assert_eq!(st, 0x01, "wrong token must not drain");
        let (st, _) = rpc(
            &mut c,
            serde_json::json!({"verb":"fpop","handle":"cc".repeat(32),"token":"wrong","max":8}),
        );
        assert_eq!(st, 0x01);

        // fput: unregistered handle, bad lengths, zero/expired deadlines.
        let future = now_sec() + 600;
        let (st, _) = rpc(
            &mut c,
            serde_json::json!({"verb":"fput","handle":"dd".repeat(32),"pointer_hex":valid_pointer(future, 2),"deadline":future}),
        );
        assert_eq!(st, 0x01, "fput at unregistered handle");
        let (st, _) = rpc(
            &mut c,
            serde_json::json!({"verb":"fput","handle":handle,"pointer_hex":"00","deadline":future}),
        );
        assert_eq!(st, 0x01, "short pointer");
        let (st, _) = rpc(
            &mut c,
            serde_json::json!({"verb":"fput","handle":handle,"pointer_hex":"01".repeat(74),"deadline":future}),
        );
        assert_eq!(st, 0x01, "bad pointer header");
        let zero = {
            let mut p = vec![1u8, 0];
            p.extend_from_slice(&[2u8; 32]);
            p.extend_from_slice(&[3u8; 32]);
            p.extend_from_slice(&0u64.to_le_bytes());
            hex::encode(p)
        };
        let (st, _) = rpc(
            &mut c,
            serde_json::json!({"verb":"fput","handle":handle,"pointer_hex":zero,"deadline":0}),
        );
        assert_eq!(st, 0x01, "zero deadline pointer");
        let (st, _) = rpc(
            &mut c,
            serde_json::json!({"verb":"fput","handle":handle,"pointer_hex":valid_pointer(1, 4),"deadline":1}),
        );
        assert_eq!(st, 0x01, "already-burned pointer (410)");

        // freg: malformed handle.
        let (st, _) = rpc(
            &mut c,
            serde_json::json!({"verb":"freg","handle":"zz","token":"t","lease":60}),
        );
        assert_eq!(st, 0x01, "non-hex handle");

        // Nothing hostile landed: the queue still drains exactly with the
        // right token and only contains nothing.
        let (st, body) = rpc(
            &mut c,
            serde_json::json!({"verb":"fpop","handle":handle,"token":token,"max":8}),
        );
        assert_eq!(st, 0x00);
        assert_eq!(body["pointers"].as_array().unwrap().len(), 0);
        drop(c);
        server.join().unwrap();
    }

    #[test]
    fn per_handle_cap_evicts_oldest() {
        let dir = mk_temp_dir("fabric-cap");
        let fcfg = FabricConfig {
            enabled: true,
            max_per_handle: 2,
            ..Default::default()
        };
        let (server, addr) = fabric_server(&dir, fcfg);
        let mut c = std::net::TcpStream::connect(&addr).unwrap();
        let handle = "ee".repeat(32);
        let token = "tok-1234567890abcdef"; // 20 bytes: within the shape rule
        rpc(
            &mut c,
            serde_json::json!({"verb":"freg","handle":handle,"token":token,"lease":60}),
        );
        let future = now_sec() + 600;
        let p1 = valid_pointer(future, 1);
        let p2 = valid_pointer(future, 2);
        let p3 = valid_pointer(future, 3);
        for p in [&p1, &p2, &p3] {
            let (st, _) = rpc(
                &mut c,
                serde_json::json!({"verb":"fput","handle":handle,"pointer_hex":p,"deadline":future}),
            );
            assert_eq!(st, 0x00);
        }
        let (st, body) = rpc(
            &mut c,
            serde_json::json!({"verb":"fpop","handle":handle,"token":token,"max":8}),
        );
        assert_eq!(st, 0x00);
        let ptrs: Vec<String> = body["pointers"]
            .as_array()
            .unwrap()
            .iter()
            .map(|x| x.as_str().unwrap().to_string())
            .collect();
        assert_eq!(ptrs, vec![p2, p3], "FIFO cap: oldest (p1) evicted");
        drop(c);
        server.join().unwrap();
    }

    #[test]
    fn freg_budget_full_refuses_without_eviction() {
        let dir = mk_temp_dir("fabric-budget");
        let fcfg = FabricConfig {
            enabled: true,
            max_regs: 2,
            ..Default::default()
        };
        let (server, addr) = fabric_server(&dir, fcfg);
        let mut c = std::net::TcpStream::connect(&addr).unwrap();
        let tok = "tok-1234567890abcdef";
        for h in ["01", "02"] {
            let (st, body) = rpc(
                &mut c,
                serde_json::json!({"verb":"freg","handle":h.repeat(32),"token":tok,"lease":60}),
            );
            assert_eq!(st, 0x00, "{body}");
        }
        // Budget is full: a NEW handle is refused (503); nothing of the live
        // regs is evicted — freg is unauthenticated and must not be a tool
        // for evicting other users.
        let (st, _) = rpc(
            &mut c,
            serde_json::json!({"verb":"freg","handle":"03".repeat(32),"token":tok,"lease":60}),
        );
        assert_eq!(st, 0x01, "full budget must refuse new registrations");
        drop(c);
        server.join().unwrap();
    }

    #[test]
    fn freg_expired_slots_swept_on_next_freg() {
        let dir = mk_temp_dir("fabric-sweep");
        let fcfg = FabricConfig {
            enabled: true,
            max_regs: 1,
            ..Default::default()
        };
        let (server, addr) = fabric_server(&dir, fcfg);
        let mut c = std::net::TcpStream::connect(&addr).unwrap();
        let tok = "tok-1234567890abcdef";
        let (st, body) = rpc(
            &mut c,
            serde_json::json!({"verb":"freg","handle":"04".repeat(32),"token":tok,"lease":1}),
        );
        assert_eq!(st, 0x00, "{body}");
        std::thread::sleep(std::time::Duration::from_millis(1200));
        // The only slot is held by an EXPIRED registration: the sweep on the
        // next freg must free it for a new handle.
        let (st, body) = rpc(
            &mut c,
            serde_json::json!({"verb":"freg","handle":"05".repeat(32),"token":tok,"lease":60}),
        );
        assert_eq!(st, 0x00, "expired slot must be swept and reusable: {body}");
        drop(c);
        server.join().unwrap();
    }

    #[test]
    fn fput_dedupe_composts_superseded_envelope_file() {
        let dir = mk_temp_dir("fabric-dedupe-disk");
        let (server, addr) = fabric_server(&dir, fabric_cfg());
        let mut c = std::net::TcpStream::connect(&addr).unwrap();
        let handle = "06".repeat(32);
        let tok = "tok-1234567890abcdef";
        rpc(
            &mut c,
            serde_json::json!({"verb":"freg","handle":handle,"token":tok,"lease":60}),
        );
        let ptr = valid_pointer(now_sec() + 600, 1);
        let (st, body) = rpc(
            &mut c,
            serde_json::json!({"verb":"fput","handle":handle,"pointer_hex":ptr,"deadline":now_sec()+600}),
        );
        assert_eq!(st, 0x00, "{body}");
        let (st, _) = rpc(
            &mut c,
            serde_json::json!({"verb":"fput","handle":handle,"pointer_hex":ptr,"deadline":now_sec()+900}),
        );
        assert_eq!(st, 0x00);
        let fenvs = |d: &std::path::Path| {
            std::fs::read_dir(d)
                .unwrap()
                .filter_map(|e| e.ok())
                .filter(|e| e.path().extension().is_some_and(|x| x == "fenv"))
                .count()
        };
        assert_eq!(
            fenvs(&dir),
            1,
            "refresh must leave exactly one envelope file"
        );
        let (st, body) = rpc(
            &mut c,
            serde_json::json!({"verb":"fpop","handle":handle,"token":tok,"max":8}),
        );
        assert_eq!(st, 0x00, "{body}");
        assert_eq!(body["pointers"].as_array().unwrap().len(), 1);
        assert_eq!(fenvs(&dir), 0, "drain composts on read");
        drop(c);
        server.join().unwrap();
    }

    #[test]
    fn expired_envelopes_compost_at_rebuild_and_drain() {
        // (a) rebuild: an envelope whose pointer deadline already passed is
        // dropped at open() and its file deleted.
        let dir = mk_temp_dir("fabric-expiry");
        let handle_hex = "07".repeat(32);
        let write_env = |deadline: u64, tag: u8| {
            let mut pb = hex::decode(valid_pointer(deadline, tag)).unwrap();
            let mut pa = [0u8; POINTER_LEN];
            pa.copy_from_slice(&pb);
            pb.clear();
            let env = Envelope {
                handle: {
                    let mut h = [0u8; 32];
                    h.copy_from_slice(&hex::decode(&handle_hex).unwrap());
                    h
                },
                pointer: pa,
                received_at: now_sec(),
            };
            let raw = marshal_envelope(&env);
            let cid = hex::encode(Sha256::digest(raw));
            std::fs::write(dir.join(format!("{cid}.fenv")), raw).unwrap();
        };
        write_env(now_sec() - 10, 1); // expired
        write_env(now_sec() + 600, 2); // live
        let st = FabricState::open(dir.to_str().unwrap(), fabric_cfg());
        {
            let queues = st.queues.lock().unwrap();
            let q = queues.get(&handle_hex).expect("live envelope rebuilt");
            assert_eq!(q.len(), 1, "expired envelope must not survive rebuild");
        }
        let fenvs: Vec<_> = std::fs::read_dir(&dir)
            .unwrap()
            .filter_map(|e| e.ok())
            .filter(|e| e.path().extension().is_some_and(|x| x == "fenv"))
            .collect();
        assert_eq!(
            fenvs.len(),
            1,
            "expired .fenv file must be deleted at rebuild"
        );

        // (b) drain: an envelope whose deadline passes while queued composts
        // at fpop instead of being delivered. Fresh dir and handle so part
        // (a)'s still-live envelope can't satisfy the drain.
        let dir_b = mk_temp_dir("fabric-expiry-drain");
        let handle_b = "09".repeat(32);
        let (server, addr) = fabric_server(&dir_b, fabric_cfg());
        let mut c = std::net::TcpStream::connect(&addr).unwrap();
        let tok = "tok-1234567890abcdef";
        rpc(
            &mut c,
            serde_json::json!({"verb":"freg","handle":handle_b,"token":tok,"lease":60}),
        );
        let p = valid_pointer(now_sec() + 2, 3);
        let (st, body) = rpc(
            &mut c,
            serde_json::json!({"verb":"fput","handle":handle_b,"pointer_hex":p,"deadline":now_sec()+2}),
        );
        assert_eq!(st, 0x00, "{body}");
        std::thread::sleep(std::time::Duration::from_millis(2100));
        let (st, body) = rpc(
            &mut c,
            serde_json::json!({"verb":"fpop","handle":handle_b,"token":tok,"max":8}),
        );
        assert_eq!(st, 0x00, "{body}");
        assert_eq!(
            body["pointers"].as_array().unwrap().len(),
            0,
            "burned envelope must compost, not deliver"
        );
        let fenvs: Vec<_> = std::fs::read_dir(&dir_b)
            .unwrap()
            .filter_map(|e| e.ok())
            .filter(|e| e.path().extension().is_some_and(|x| x == "fenv"))
            .collect();
        assert_eq!(
            fenvs.len(),
            0,
            "drained-and-composted envelope gone from disk"
        );
        drop(c);
        server.join().unwrap();
    }

    #[test]
    fn handle_case_is_not_identity() {
        // Register with mixed-case hex; publish and drain with lowercase.
        // If case split the namespace, fput would 404 and the pointer would
        // strand at a second "identity".
        let dir = mk_temp_dir("fabric-case");
        let (server, addr) = fabric_server(&dir, fabric_cfg());
        let mut c = std::net::TcpStream::connect(&addr).unwrap();
        let upper = "AB".repeat(32);
        let lower = "ab".repeat(32);
        let tok = "tok-1234567890abcdef";
        let (st, body) = rpc(
            &mut c,
            serde_json::json!({"verb":"freg","handle":upper,"token":tok,"lease":60}),
        );
        assert_eq!(st, 0x00, "{body}");
        let p = valid_pointer(now_sec() + 600, 1);
        let (st, body) = rpc(
            &mut c,
            serde_json::json!({"verb":"fput","handle":lower,"pointer_hex":p,"deadline":now_sec()+600}),
        );
        assert_eq!(st, 0x00, "case must normalize to one handle slot: {body}");
        let (st, body) = rpc(
            &mut c,
            serde_json::json!({"verb":"fpop","handle":upper,"token":tok,"max":8}),
        );
        assert_eq!(st, 0x00, "{body}");
        assert_eq!(body["pointers"].as_array().unwrap().len(), 1);
        drop(c);
        server.join().unwrap();
    }

    #[test]
    fn fpop_shares_fput_rate_window() {
        let dir = mk_temp_dir("fabric-fpop-rate");
        let fcfg = FabricConfig {
            enabled: true,
            fput_rate: 2,
            ..Default::default()
        };
        let (server, addr) = fabric_server(&dir, fcfg);
        let mut c = std::net::TcpStream::connect(&addr).unwrap();
        // fpop is an unauthenticated parser path: it shares fput's per-IP
        // window so flooding it is no cheaper than flooding fput.
        for _ in 0..2 {
            let (st, _) = rpc(
                &mut c,
                serde_json::json!({"verb":"fpop","handle":"08".repeat(32),"token":"x","max":8}),
            );
            assert_eq!(st, 0x01, "404 path still consumes budget");
        }
        let (st, _) = rpc(
            &mut c,
            serde_json::json!({"verb":"fpop","handle":"08".repeat(32),"token":"x","max":8}),
        );
        assert_eq!(st, 0x01, "429 after window exhausted");
        drop(c);
        server.join().unwrap();
    }

    #[test]
    fn fabric_state_rebuilds_from_disk() {
        // Restart safety: envelopes persisted as .fenv survive a state drop
        // and rebuild into the in-memory index in FIFO order.
        let dir = mk_temp_dir("fabric-rebuild");
        let handle_hex = "ff".repeat(32);
        let ptr_a = valid_pointer(now_sec() + 600, 1);
        let ptr_b = valid_pointer(now_sec() + 600, 2);
        for (i, p) in [&ptr_a, &ptr_b].iter().enumerate() {
            let mut pb = hex::decode(p).unwrap();
            let mut pa = [0u8; POINTER_LEN];
            pa.copy_from_slice(&pb);
            pb.clear();
            let env = Envelope {
                handle: {
                    let mut h = [0u8; 32];
                    h.copy_from_slice(&hex::decode(&handle_hex).unwrap());
                    h
                },
                pointer: pa,
                received_at: 1000 + i as u64,
            };
            let raw = marshal_envelope(&env);
            let cid = hex::encode(Sha256::digest(raw));
            std::fs::write(dir.join(format!("{cid}.fenv")), raw).unwrap();
        }
        let st = FabricState::open(dir.to_str().unwrap(), fabric_cfg());
        let queues = st.queues.lock().unwrap();
        let q = queues.get(&handle_hex).expect("rebuilt queue");
        assert_eq!(q.len(), 2);
        assert_eq!(hex::encode(q[0].pointer), *ptr_a, "FIFO order preserved");
        assert_eq!(hex::encode(q[1].pointer), *ptr_b);
    }

    #[test]
    fn zero_salt_hkdf_matches_go() {
        // Direct pin that Extract uses a ZERO salt: derive a handle from a
        // trivially known key and compare against a hand-computed RFC 5869
        // PRK (HMAC(0x00*32, ikm)). If someone "fixes" the salt to ikm or a
        // string, the Go interop breaks and this catches it.
        let ikm = [7u8; 32];
        let prk = hkdf_prk(&ikm);
        let expect = hmac_sha256(&[0u8; 32], &ikm);
        assert_eq!(prk, expect);
    }
}
